### ISSUE TITLE
OpenDataHack2018-Challenges

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/Brainstorm#11]
https://github.com/OpenDataHack2018/OpenDataHack2018-Challenges

Da um a olhada

Sera que poderiamos organizar algo assim na USP? Tem algo assim ja funcionando?

**Comment by Schuch666** [comment]
como assim?

**Comment by ibarraespinosa** [comment]
Um OpenDataHack. Eles fazem uma competição. 24 horas continuas de hacking para visualizar, criar o fazer algomis. são 3 categorias. Deve ser bem legal

**Comment by Schuch666** [comment]
Perece ser bem legal, vamos fazer isso uma hora? poderíamos convidar mais gente (ou não) mas teríamos que achar um lugar para todo mundo se reunir
