### ISSUE TITLE
Pacote para processar dados de satelite

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/Brainstorm#5]
Sería bom cirar um pacote para processar dados de satelite e poluição do ar?

**Comment by Schuch666** [comment]
não vou falar que dá p fazer no EmissV (mas dá para fazer!), mas temos que falar com aquela pesquisadora, combinar uma reunião para mostrar o atmoschem e perguntar se ela tem interece em colocar isso no atmoschem

**Comment by Schuch666** [comment]
@ibarraespinosa qual era a pesquisadora msm? (acho que já conversamos sobre isso)

**Comment by ibarraespinosa** [comment]
sera a Marcia Akemi?
