### ISSUE TITLE
WRF-R?

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/Brainstorm#9]
Tem um modelo de Python com un nome chamativo: WRF-Python. Quando li ele pensei, nossa, será que eles portaram o WRF para Python?? Não pode ser... eu ai vi e só era um modelo para visualizar as saidas. Eu não vi em detalhe, se tem interpolação o mais, so que tenho certeza que exportando os dados espacialmente com stars, daria resultados ainda melhores, pos não sería perdida a referencia espacial. 

http://wrf-python.readthedocs.io/en/latest/

**Este possivel pacote não vai ter o nome WRF-R**

Observação: o UCAR esta ensinando ele como parte do workshop de WRF, com valor de inscrição de 250 USD
https://www.mmm.ucar.edu/joint-wrf-and-mpas-users-workshop

**Comment by Schuch666** [comment]
Eu acho uma ideia muito boa, teriamos que pensar bem no que iriamos incluir
